 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ULTRASONIC  driver
 *
 * Author: Mohamed Ahmed Hassan Aboelnaga
 *
 *******************************************************************************/

#include"ultrasonic.h"
#include"icu.h"
#include"gpio.h"
#include <util/delay.h>


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/*global variable that stores the high value of the echo pin (measured by the Icu)  */
static uint16 g_echo_time = 0;

/*global variable that increment each interrupt to count the number of edges  */
static uint8 g_edge_count;



/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/

/*Description
 *
 Initialize the ICU driver as required.
 Setup the ICU call back function.
 Setup the direction for the trigger pin as output pin through the
GPIO driver.
Inputs: None
Return:None
 */
void Ultrasonic_init(void)
{
	/* Initialize the ICU driver */
	Icu_ConfigType config={F_CPU_8,RISING};
	Icu_init(&config);

	/* Setup the ICU call back function
	 * this is the function that will be called each edge or each interrupt */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup the direction for the trigger pin as output pin*/
	GPIO_setupPinDirection(TRIGGER_PORT,TRIGGER_PIN ,PIN_OUTPUT);

	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN ,LOGIC_LOW); //initially

	/* note: no need to setup direction of echo pin as Icu_init() do that	 */
}



/*
 Description
 Send the Trigger pulse to the ultrasonic.
 Inputs: None
 Return:None
 */
void Ultrasonic_Trigger(void)
{
	/*The pulse is  generated by writing on  the pin logic high then delay with (TRIGGER_PULSE_DURATION)
	 * then writing on  the pin logic low */
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN ,LOGIC_HIGH);
	_delay_us(TRIGGER_PULSE_DURATION);
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN ,LOGIC_LOW);
}




/* Description
 Send the trigger pulse by using Ultrasonic_Trigger function.
 Start the measurements by the ICU from this moment.
 Inputs: None
 Return: The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void)
{ /* Send the trigger pulse by using Ultrasonic_Trigger function */
	Ultrasonic_Trigger();

	/* Start the measurements by the ICU from this moment.
	 *
	 * Calculation (distance in cm)
Sound velocity = 346.00 m/s = 34600 cm/s
The distance of Object (in cm) = 346000∗Time /2 = 17300 * Time
Now, here we have selected an internal 8MHz oscillator frequency for ATmega32, with
Prescaler F_CPU/8 for timer frequency. Then time to execute 1 instruction is 1 us.
So, the timer gets incremented after 1 us time elapse.
= 17300 x (TIMER value) x 1 x 10^-6 cm
= 0.0173 x (TIMER value) cm
Note TIMER VALUE is the pulse width time calculated by the ICU.
	 */

	/* return the value of the distance using the echo high time calculated by the icu */
	return(0.0173*g_echo_time)	;

}




/*
Description
 This is the call back function called by the ICU driver.
 This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
 Inputs: None
 Return: None
 */
void Ultrasonic_edgeProcessing(void)
{ /* this is the first high edge, you should start the timer here and make it work next with falling edge */
	g_edge_count++;//count the edges (interrupts)
	if(g_edge_count==1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}

	else if(g_edge_count==2)
	{ /* here you catch the falling edge of the echo pin which means you now have the high time
		so you should store it in your global variable to read it*/
		g_echo_time=Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
		g_edge_count=0;
	}
}
